from fastapi import APIRouter

from app.schemas.chat import ChatRequest, ChatResponse
from app.services.llm import generate_response

router = APIRouter()

@router.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Endpoint to handle chat requests.

    Args:
        request (ChatRequest): The chat request containing the user's message.

    Returns:
        ChatResponse: The response generated by the language model.
    """
    user_message = request.message
    response_text = generate_response(user_message)
    return ChatResponse(response=response_text)