from fastapi import APIRouter

from app.schemas.chat import ChatRequest, ChatResponse
from app.services.llm import generate_response, stream_response
from fastapi.responses import StreamingResponse
router = APIRouter()

@router.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Endpoint to handle chat requests.

    Args:
        request (ChatRequest): The chat request containing the user's message.

    Returns:
        ChatResponse: The response generated by the language model.
    """
    response = generate_response(request.messages)

    return ChatResponse(response=response)

@router.post("/chat/stream")
async def chat_stream(request: ChatRequest):

    return StreamingResponse(
        stream_response(request.messages),
        media_type="text/event-stream",
    )